# see http://about.travis-ci.org/docs/user/languages/python/ for more hints
language: python

python:
  # using major version aliases
  - "3.3"
  - "3.4"
  - "3.5"

script: "python -m unittest"

install:
  - pip install pytest-cov

after_success:
    py.test --cov=./
    codecov -t db9d21de-595d-4797-b4df-cdf32854c3dd